name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend bağımlılıklarını kur
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Frontend bağımlılıklarını kur
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Backend testleri
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test || echo "No backend tests"

      # Frontend testleri
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test || echo "No frontend tests"

      # Vercel deploy
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
